name: '$(Date:yyyyMMdd HHmmss) commit-$(Build.SourceVersion)'

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  displayName: Update .csproj Versions
  inputs:
    filePath: 'ci\update-csproj-versions.ps1'
    arguments: '-SrcDirectory $(System.DefaultWorkingDirectory)\src -BuildId $(Build.BuildId) -InformationalVersionSuffix FOOBAR'

- task: DotNetCoreCLI@2
  displayName: Publish WebApi
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src\BrickScan.WebApi\BrickScan.WebApi.csproj'
    arguments: '-c $(buildConfiguration) /p:Platform=x64 --output $(Build.ArtifactStagingDirectory) -r linux-x64'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  displayName: Publish BrickScan WPF Client
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src\BrickScan.WpfClient\BrickScan.WpfClient.csproj'
    arguments: '-c $(buildConfiguration) /p:Platform=x64 --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: CopyFiles@2
  displayName: Copy CI data to Artifacts Staging 
  inputs:
    SourceFolder: 'ci'
    Contents: '**/*.ps1'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ci'

- task: CopyFiles@2 
  displayName: Copy squirrel.windows package to Artifacts Staging 
  inputs:
    SourceFolder: '$(UserProfile)\.nuget\packages'
    Contents: 'squirrel*/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\packages'

- task: CmdLine@2
  displayName: CMD Create EF Core migration script
  inputs:
    script: |
      dotnet tool install --global dotnet-ef
      dotnet ef migrations script -i -o $(Build.ArtifactStagingDirectory)\BrickScan.Library.Dataset\migrate.sql -p src\BrickScan.WebApi\BrickScan.WebApi.csproj

- task: DeleteFiles@1
  displayName: Delete Tensorflow linux-x64 runtimes
  enabled: false
  inputs:
    SourceFolder: 'runtimes\linux-x64\'
    Contents: '*'
    RemoveSourceFolder: True

- task: DeleteFiles@1
  enabled: false
  displayName: Delete Tensorflow Unused runtimes
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)\BrickScan.WebApi\runtimes\'
    Contents: |
      osx*\**
      unix*\**
      win*\**

    RemoveSourceFolder: True
       
- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
