trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
    
- task: CopyFiles@2
  displayName: Copy to artifacts staging directory
  inputs:
    SourceFolder: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
    Contents: src\BrickScan.WebApi\bin\$(BuildConfiguration)\netcoreapp3.1\**
    TargetFolder: '$(BUILD.ARTIFACTSTAGINGDIRECTORY)'

- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    PathtoPublish: '$(BUILD.ARTIFACTSTAGINGDIRECTORY)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
