trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  displayName: Update .csproj Versions
  inputs:
    filePath: 'ci\update-csproj-versions.ps1'
    arguments: '-SrcDirectory $(System.DefaultWorkingDirectory)\src -BuildId $(Build.BuildId) -InformationalVersionSuffix FOOBAR'

- task: DotNetCoreCLI@2
  displayName: Publish WebApi
  enabled: false
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -r win-x64'
    zipAfterPublish: False

- task: DotNetCoreCLI@2
  displayName: Publish BrickScan WPF Client
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src\BrickScan.WpfClient\BrickScan.WpfClient.csproj'
    arguments: '-c $(buildConfiguration) /p:Platform=x64 --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: NuGetCommand@2
  displayName: Pack WPF Client Squirrel Package
  enabled: false
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.ArtifactStagingDirectory)\BrickScan.WpfClient\BrickScan.WpfClient.Squirrel.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)\BrickScan.WpfClient'
    versioningScheme: 'off'

- task: CopyFiles@2
  displayName: Copy CI data to Artifacts Staging 
  inputs:
    SourceFolder: 'ci'
    Contents: '**/*.ps1'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ci'

- task: CopyFiles@2 
  displayName: Copy squirrel.windows package to Artifacts Staging 
  inputs:
    SourceFolder: '$(UserProfile)\.nuget\packages'
    Contents: 'squirrel*/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\packages'

- task: DeleteFiles@1
  displayName: Delete Tensorflow linux-x64 runtimes
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)\BrickScan.WebApi\runtimes\linux-x64\'
    Contents: '*'
    RemoveSourceFolder: True

- task: DeleteFiles@1
  displayName: Delete Tensorflow osx-x64 runtimes
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)\BrickScan.WebApi\runtimes\osx-x64\'
    Contents: '*'
    RemoveSourceFolder: True
       
- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
