trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: NuGetCommand@2
  displayName: "Restore NuGet Packages"
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Publish WebApi
  enabled: False
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) -r win-x64'
    zipAfterPublish: False

- task: DotNetCoreCLI@2
  displayName: Publish BrickScan WPF Client
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src\BrickScan.WpfClient\BrickScan.WpfClient.csproj'
    arguments: '-c $(buildConfiguration) /p:Platform=x64 --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: NuGetCommand@2
  displayName: Pack WPF Client Squirrel Package
  enabled: false
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.ArtifactStagingDirectory)\BrickScan.WpfClient\BrickScan.WpfClient.Squirrel.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)\BrickScan.WpfClient'
    versioningScheme: 'off'

- task: CopyFiles@2 
  displayName: Copy squirrel.windows packages tool directory  
  inputs:
    SourceFolder: 'packages'
    Contents: 'squirrel.windows.*\tools'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\packages'

- task: DeleteFiles@1
  displayName: Delete Tensorflow linux-x64 runtimes
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)\BrickScan.WebApi\runtimes\linux-x64\'
    Contents: '*'
    RemoveSourceFolder: True

- task: DeleteFiles@1
  displayName: Delete Tensorflow osx-x64 runtimes
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)\BrickScan.WebApi\runtimes\osx-x64\'
    Contents: '*'
    RemoveSourceFolder: True
       
- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
    PathtoPublish: '$(BUILD.ARTIFACTSTAGINGDIRECTORY)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
