//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickScan.WpfClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickScan.WpfClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active inventory service.
        /// </summary>
        public static string ActiveInventoryServiceType {
            get {
                return ResourceManager.GetString("ActiveInventoryServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 1st train image to display images.
        /// </summary>
        public static string Add1stTrainImageToDisplayImages {
            get {
                return ResourceManager.GetString("Add1stTrainImageToDisplayImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new complementary part..
        /// </summary>
        public static string AddComplementaryPartToolTip {
            get {
                return ResourceManager.GetString("AddComplementaryPartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        public static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parts.
        /// </summary>
        public static string AddParts {
            get {
                return ResourceManager.GetString("AddParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a dialog to add this part to your inventory..
        /// </summary>
        public static string AddToInventoryToolTip {
            get {
                return ResourceManager.GetString("AddToInventoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying update.
        /// </summary>
        public static string ApplyingUpdate {
            get {
                return ResourceManager.GetString("ApplyingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average (last 6 month).
        /// </summary>
        public static string AvgSold {
            get {
                return ResourceManager.GetString("AvgSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average (current).
        /// </summary>
        public static string AvgStock {
            get {
                return ResourceManager.GetString("AvgStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base color.
        /// </summary>
        public static string BaseColor {
            get {
                return ResourceManager.GetString("BaseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bricklink API.
        /// </summary>
        public static string BricklinkApi {
            get {
                return ResourceManager.GetString("BricklinkApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bricklink API integration.
        /// </summary>
        public static string BricklinkApiIntegration {
            get {
                return ResourceManager.GetString("BricklinkApiIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bricklink summary.
        /// </summary>
        public static string BricklinkSummary {
            get {
                return ResourceManager.GetString("BricklinkSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bricklink XML file.
        /// </summary>
        public static string BricklinkXml {
            get {
                return ResourceManager.GetString("BricklinkXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrickScan.
        /// </summary>
        public static string BrickScan {
            get {
                return ResourceManager.GetString("BrickScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrickScan homepage..
        /// </summary>
        public static string BrickScanHomepage {
            get {
                return ResourceManager.GetString("BrickScanHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrickScan on GitHub..
        /// </summary>
        public static string BrickScanOnGithub {
            get {
                return ResourceManager.GetString("BrickScanOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect USB camera..
        /// </summary>
        public static string CannotConnectCameraTooltip {
            get {
                return ResourceManager.GetString("CannotConnectCameraTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color scheme.
        /// </summary>
        public static string ColorScheme {
            get {
                return ResourceManager.GetString("ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that the input image is this part..
        /// </summary>
        public static string ConfirmImageBelongsToClassToolTip {
            get {
                return ResourceManager.GetString("ConfirmImageBelongsToClassToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects the selected USB camera..
        /// </summary>
        public static string ConnectCameraTooltip {
            get {
                return ResourceManager.GetString("ConnectCameraTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Bricklink inventory lot.
        /// </summary>
        public static string CreateNewBricklinkInventory {
            get {
                return ResourceManager.GetString("CreateNewBricklinkInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom RESTful API.
        /// </summary>
        public static string CustomRestApi {
            get {
                return ResourceManager.GetString("CustomRestApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default condition.
        /// </summary>
        public static string DefaultConditionForInventory {
            get {
                return ResourceManager.GetString("DefaultConditionForInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display images.
        /// </summary>
        public static string DisplayImages {
            get {
                return ResourceManager.GetString("DisplayImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new release.
        /// </summary>
        public static string DownloadingNewRelease {
            get {
                return ResourceManager.GetString("DownloadingNewRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to edit profile. Please sign out and then sign in again and try again..
        /// </summary>
        public static string EditProfileFailedMessage {
            get {
                return ResourceManager.GetString("EditProfileFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string ErrorOccurredCaption {
            get {
                return ResourceManager.GetString("ErrorOccurredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I generate the access token?.
        /// </summary>
        public static string HowToGenerateAccessTokens {
            get {
                return ResourceManager.GetString("HowToGenerateAccessTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified part summary.
        /// </summary>
        public static string IdentifiedPartSummary {
            get {
                return ResourceManager.GetString("IdentifiedPartSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify.
        /// </summary>
        public static string Identify {
            get {
                return ResourceManager.GetString("Identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        public static string ImageFiles {
            get {
                return ResourceManager.GetString("ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size.
        /// </summary>
        public static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error. Please try again in a moment..
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory integration.
        /// </summary>
        public static string InventoryIntegration {
            get {
                return ResourceManager.GetString("InventoryIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off..
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on..
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves this image to the first position..
        /// </summary>
        public static string MoveTopToolTip {
            get {
                return ResourceManager.GetString("MoveTopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged on.
        /// </summary>
        public static string NotLoggedOn {
            get {
                return ResourceManager.GetString("NotLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No USB camera selected..
        /// </summary>
        public static string NoUsbCameraSelectedTooltip {
            get {
                return ResourceManager.GetString("NoUsbCameraSelectedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bricklink page.
        /// </summary>
        public static string OpenOnBricklink {
            get {
                return ResourceManager.GetString("OpenOnBricklink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Bricklink page of this part..
        /// </summary>
        public static string OpenOnBricklinkToolTip {
            get {
                return ResourceManager.GetString("OpenOnBricklinkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part number.
        /// </summary>
        public static string PartNo {
            get {
                return ResourceManager.GetString("PartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price fixing.
        /// </summary>
        public static string PriceFixing {
            get {
                return ResourceManager.GetString("PriceFixing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per part.
        /// </summary>
        public static string PricePerPart {
            get {
                return ResourceManager.GetString("PricePerPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program version.
        /// </summary>
        public static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity average (last 6 month).
        /// </summary>
        public static string QuantityAvgSold {
            get {
                return ResourceManager.GetString("QuantityAvgSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity average (current).
        /// </summary>
        public static string QuantityAvgStock {
            get {
                return ResourceManager.GetString("QuantityAvgStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying existing Bricklink inventory....
        /// </summary>
        public static string QueryingBricklinkInventory {
            get {
                return ResourceManager.GetString("QueryingBricklinkInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickstart guide.
        /// </summary>
        public static string QuickstartGuide {
            get {
                return ResourceManager.GetString("QuickstartGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed..
        /// </summary>
        public static string RequestFailedMessage {
            get {
                return ResourceManager.GetString("RequestFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} was installed successfully. A restart of the application is required to finish the update..
        /// </summary>
        public static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running identification....
        /// </summary>
        public static string RunningIdentificationMessage {
            get {
                return ResourceManager.GetString("RunningIdentificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image....
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending data to the server....
        /// </summary>
        public static string SendingData {
            get {
                return ResourceManager.GetString("SendingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity.
        /// </summary>
        public static string Sensitivity {
            get {
                return ResourceManager.GetString("Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage/bin.
        /// </summary>
        public static string StorageOrBin {
            get {
                return ResourceManager.GetString("StorageOrBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission failed..
        /// </summary>
        public static string SubmissionFailedMessage {
            get {
                return ResourceManager.GetString("SubmissionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission successful. Thank you!.
        /// </summary>
        public static string SubmissionSuccessfulMessage {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests. Please wait a few seconds and try again..
        /// </summary>
        public static string TooManyRequestsErrorMessage {
            get {
                return ResourceManager.GetString("TooManyRequestsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted total quantity = {0}..
        /// </summary>
        public static string TotalQuantitySubmitted {
            get {
                return ResourceManager.GetString("TotalQuantitySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training images.
        /// </summary>
        public static string TrainImages {
            get {
                return ResourceManager.GetString("TrainImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Bricklink inventory lot (ID = {0}, quantity = {1}).
        /// </summary>
        public static string UpdateBricklinkInventory {
            get {
                return ResourceManager.GetString("UpdateBricklinkInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use as default inventory.
        /// </summary>
        public static string UseAsDefaultInventory {
            get {
                return ResourceManager.GetString("UseAsDefaultInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        public static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for confirmation....
        /// </summary>
        public static string WaitingForConfirmationResponse {
            get {
                return ResourceManager.GetString("WaitingForConfirmationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
